"""create health_checks table

Revision ID: df4bd842b27a
Revises: 
Create Date: 2025-09-16 12:20:33.780220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df4bd842b27a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_checks',
    sa.Column('check_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('check_datetime', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('check_id')
    )
    op.create_index(op.f('ix_health_checks_check_id'), 'health_checks', ['check_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_health_checks_check_id'), table_name='health_checks')
    op.drop_table('health_checks')
    # ### end Alembic commands ###
